name: utapatents
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Dependências do Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.14.3
  
flutter_local_notifications: ^9.1.4
table_calendar: ^3.0.9
image_picker: ^0.8.7+5
dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote "flutter_lints" contém uma lista de recomendações de lint
  flutter_lints: ^5.0.0

flutter:
  # Garante que os ícones do Material sejam incluídos
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  
fonts:
    - family: Rye
      fonts:
        - asset: assets/fonts/Rye-Regular.ttf