// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjPZvDEQXogpzU6FMcr_sGdxjan8y_aI',
    appId: '1:305918385377:web:55afaf28757db30d912ba0',
    messagingSenderId: '305918385377',
    projectId: 'uta-patents',
    authDomain: 'uta-patents.firebaseapp.com',
    storageBucket: 'uta-patents.firebasestorage.app',
    measurementId: 'G-872JMBX21H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bQ4aIpvXCXui39B7DmfqdYUX3Y7ADjM',
    appId: '1:305918385377:android:616cdfdf8580d7cd912ba0',
    messagingSenderId: '305918385377',
    projectId: 'uta-patents',
    storageBucket: 'uta-patents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxFzbJvTNtufR52PmTql_XyPwA554WOE',
    appId: '1:305918385377:ios:5d5b97f48179eb1e912ba0',
    messagingSenderId: '305918385377',
    projectId: 'uta-patents',
    storageBucket: 'uta-patents.firebasestorage.app',
    iosBundleId: 'com.example.utapatents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhxFzbJvTNtufR52PmTql_XyPwA554WOE',
    appId: '1:305918385377:ios:5d5b97f48179eb1e912ba0',
    messagingSenderId: '305918385377',
    projectId: 'uta-patents',
    storageBucket: 'uta-patents.firebasestorage.app',
    iosBundleId: 'com.example.utapatents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNMNCYNAxWDeryjXf2dMA6Oj_fUmgXFpw',
    appId: '1:305918385377:web:c63dd989ce3a7f45912ba0',
    messagingSenderId: '305918385377',
    projectId: 'uta-patents',
    authDomain: 'uta-patents.firebaseapp.com',
    storageBucket: 'uta-patents.firebasestorage.app',
    measurementId: 'G-2V6C4RTXY6',
  );
}
